sudo: false
language: ruby
rvm:
- 2.0.0
before_install: gem install bundler -v 1.12.5
script:
- bundle exec rake spec
- bundle exec rubocop
deploy:
  provider: rubygems
  api_key:
    secure: Jz0lM8uxp2T+Ek5AOAHTV6guOtx4C008n4X4Pa8BUc/Vki30CSBmgBwBvOzBGNjpnlKPK3hZsMegB1V1uYnB1FfXDxKGUWiEtOJ5YDAWnMXPfCwo7GUlykVc9fAAzERDc/Wr7IYZjsWga7iLga3NOdk/LIlvfjnWJzKDM7rWQ11T9qv8Jcpiq4kv8qgrZK1zbxNEpXL4PZfuBqm4tByCR2isxlUTUBzXque6YF3tQ9Xx6K+u/Jt9uONqSEcKpasJpbUmnKYynubX0JYT5qT+ZK+T93xAtXHQ7FXxDKy8hFu3Co3diBYZis80KRNGNK/oL1loB2jN2iGOvHs4FGMUQ4eVZZk7bxZpFeYmc0j83iGfEXWyRPYMIYstUl6+HFM7A3Ques3feF7zcMAVN5KzBGADEuGcLt/Qyy7ogGDBwgw9DNxK+xq+rkIZZhW7MhCbWu24b5lUh9sZectxRIoUr/67aT+wbB5sBEfyb8WsPX+FIlevx7bW+MbOn96pXxs8SAWMPy4XRCPB+6zD7OpgsbL0UlK3Z9kbVXFcguyox5jmmf3uJKykwwCZAtJspPjkxmBWwM3NjDhQNxf/GaGQ/DP8YeiOHVNZyxD7JyxzEnt1lvs+36Lm0sab6rtRJiBHyHjCs/NKWO5to+BVOY34jGpGl6ncnXsK6mgcMVoADgw=
  gem: metrobus
  on:
    tags: true
    repo: sbower/metrobus
